import type { IconType } from 'react-icons'
import { PiDropFill, PiFireFill, PiWindFill, PiEyeFill, PiMeteorFill, PiLightningFill, PiBiohazardFill, PiSkullFill } from 'react-icons/pi'
import { BsWater, BsArrowThroughHeartFill, BsEmojiHeartEyesFill } from 'react-icons/bs'
import { MdFlood } from 'react-icons/md'
import { FaSun, FaIcicles, FaMountain, FaSnowman, FaHeart } from 'react-icons/fa'
import { FaBottleWater, FaHurricane } from 'react-icons/fa6'
import { GiWaveSurfer, GiFireDash, GiStonePile, GiDefensiveWall, GiLightningFlame, GiLightningDome, GiThunderSkull, GiMeltingIceCube, GiSnowing, GiAppleCore, GiPoisonGas, GiTimeSynchronization, GiBlackHoleBolas, GiFallingStar, GiStoneSphere, GiLoveInjection, GiChainedHeart } from 'react-icons/gi'
import { TbTornado, TbTemperatureMinusFilled, TbDeviceLaptop, TbCloudRain, TbBrandSupernova } from 'react-icons/tb'
import { WiFog } from 'react-icons/wi'
import { SiBunnydotnet, SiSaturn } from 'react-icons/si'
import { RiEarthquakeFill, RiSnowflakeFill, RiRewindStartFill } from 'react-icons/ri'
import { CiClock2 } from 'react-icons/ci'
import { CgSandClock } from 'react-icons/cg'
import { LiaUserTimesSolid } from 'react-icons/lia'
import { GiCardJoker, GiJesterHat, GiTopHat, GiBalloons, GiClown, GiSunbeams, GiSunrise, GiSunRadiations, GiCandleLight, GiHolyGrail, GiNightSky, GiRaven, GiMoonBats, GiShadowFollower, GiEclipse } from 'react-icons/gi'

export interface ClientAbilityMetadata {
  id: string
  name: string
  description: string
  hotkey: string
  kind: 'attack' | 'utility' | 'ultimate' | 'passive'
  element: string
  color: string // theme color hex
  gradient: string // CSS gradient for buttons
  icon: IconType // react-icons component rendered on the ability card
  /**
   * Charge-based casts (Lightning Barrage): the card shows mini cast buttons
   * for spending 1/2/3 charges. This flag only says the ability HAS charges —
   * the pool size, per-charge price, damage table, and regen cadence are all
   * server-derived (`GamePlayer.abilityPrices[id].charges`).
   */
  charges?: true
}

export const ABILITY_METADATA: Record<string, ClientAbilityMetadata> = {
  // Water Abilities
  waterBall: {
    id: 'waterBall',
    name: 'Water Ball',
    description: 'Basic Water attack. Hurls a sphere of compressed water at your target.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'water',
    color: '#4aa3ff',
    gradient: 'linear-gradient(135deg, #1e3c72, #2a5298, #4aa3ff)',
    icon: PiDropFill,
  },
  waterfall: {
    id: 'waterfall',
    name: 'Waterfall',
    description: 'Powerful Water attack that applies Current. While caught in a Current, your Water attacks heal your castle based on damage dealt, and Flood lasts longer against them.',
    hotkey: 'W',
    kind: 'attack',
    element: 'water',
    color: '#4aa3ff',
    gradient: 'linear-gradient(135deg, #2b5876, #4e4376, #4aa3ff)',
    icon: BsWater,
  },
  flood: {
    id: 'flood',
    name: 'Flood',
    description: 'Heavy Water attack. Washes over the target, preventing them from targeting you for a few seconds — even longer if they are caught in a Current.',
    hotkey: 'E',
    kind: 'attack',
    element: 'water',
    color: '#4aa3ff',
    gradient: 'linear-gradient(135deg, #0f2027, #203a43, #2c5364)',
    icon: MdFlood,
  },
  fluidAssimilation: {
    id: 'fluidAssimilation',
    name: 'Fluid Assimilation',
    description: 'Dissolve into the surrounding moisture: no enemy can attack you for 5 seconds.',
    hotkey: 'R',
    kind: 'utility',
    element: 'water',
    color: '#4aa3ff',
    gradient: 'linear-gradient(135deg, #2193b0, #6dd5ed)',
    icon: FaBottleWater,
  },
  riptide: {
    id: 'riptide',
    name: 'Riptide',
    description: 'The tide turns in your favor: restore half your castle health and draw new citizens to your banner.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'water',
    color: '#4aa3ff',
    gradient: 'linear-gradient(135deg, #00c6ff, #0072ff)',
    icon: GiWaveSurfer,
  },

  // Fire Abilities
  fireball: {
    id: 'fireball',
    name: 'Fireball',
    description: 'Basic Fire attack. Launches a searing fireball at your target.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'fire',
    color: '#ff6b4a',
    gradient: 'linear-gradient(135deg, #870000, #190000, #ff6b4a)',
    icon: PiFireFill,
  },
  scorchingSun: {
    id: 'scorchingSun',
    name: 'Scorching Sun',
    description: 'Powerful Fire attack that guarantees Burn on the target.',
    hotkey: 'W',
    kind: 'attack',
    element: 'fire',
    color: '#ff6b4a',
    gradient: 'linear-gradient(135deg, #f12711, #f5af19)',
    icon: FaSun,
  },
  firenado: {
    id: 'firenado',
    name: 'Firenado',
    description: 'Very powerful Fire attack with a chance to apply Burn. Burning targets take damage over time and suffer extra from your Fire attacks.',
    hotkey: 'E',
    kind: 'attack',
    element: 'fire',
    color: '#ff6b4a',
    gradient: 'linear-gradient(135deg, #f857a6, #ff5858)',
    icon: TbTornado,
  },
  heatWave: {
    id: 'heatWave',
    name: 'Heat Wave',
    description: 'Superheat the air around your castle, temporarily raising your critical hit chance and critical damage. Cannot stack.',
    hotkey: 'R',
    kind: 'utility',
    element: 'fire',
    color: '#ff6b4a',
    gradient: 'linear-gradient(135deg, #ff9966, #ff5e62)',
    icon: TbTemperatureMinusFilled,
  },
  blazingDetermination: {
    id: 'blazingDetermination',
    name: 'Blazing Determination',
    description: 'Pour everything into a single strike — your next attack deals massively increased damage.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'fire',
    color: '#ff6b4a',
    gradient: 'linear-gradient(135deg, #e52d27, #b31217)',
    icon: GiFireDash,
  },

  // Air Abilities
  aLightBreeze: {
    id: 'aLightBreeze',
    name: 'A Light Breeze',
    description: 'Basic Air attack. Slices the target with compressed wind currents. While Bird\'s Eye View is active, a multi-kingdom cast ricochets between the selected kingdoms — full damage each landing, 50% to bounce again (up to 4 hits), never the same castle twice in a row.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'air',
    color: '#b7c9ff',
    gradient: 'linear-gradient(135deg, #4b6cb7, #182848)',
    icon: PiWindFill,
  },
  hurricane: {
    id: 'hurricane',
    name: 'Hurricane',
    description: 'Powerful Air attack. The next time the victim attacks you, their attack is guaranteed to be deflected into another kingdom instead.',
    hotkey: 'W',
    kind: 'attack',
    element: 'air',
    color: '#b7c9ff',
    gradient: 'linear-gradient(135deg, #83a4d4, #b6fbff)',
    icon: FaHurricane,
  },
  thickFog: {
    id: 'thickFog',
    name: 'Thick Fog',
    description: 'Moderate Air attack that blankets the target\'s screen in fog, hiding battlefield information from them for a short time. Up to three players can be fogged at once.',
    hotkey: 'E',
    kind: 'attack',
    element: 'air',
    color: '#b7c9ff',
    gradient: 'linear-gradient(135deg, #6190e8, #a7bfe8)',
    icon: WiFog,
  },
  birdsEyeView: {
    id: 'birdsEyeView',
    name: "Bird's Eye View",
    description: 'Rise above the clouds to temporarily reveal every kingdom\'s castle HP, shields, citizens, and income.',
    hotkey: 'R',
    kind: 'utility',
    element: 'air',
    color: '#b7c9ff',
    gradient: 'linear-gradient(135deg, #2b5876, #4e4376)',
    icon: PiEyeFill,
  },
  dustBunnies: {
    id: 'dustBunnies',
    name: 'Dust Bunnies',
    description: 'Send dust bunnies scurrying into every opposing kingdom, slowly gnawing away at them with damage over time.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'air',
    color: '#b7c9ff',
    gradient: 'linear-gradient(135deg, #3a7bd5, #3a6073)',
    icon: SiBunnydotnet,
  },

  // Earth Abilities
  rockThrow: {
    id: 'rockThrow',
    name: 'Rock Throw',
    description: 'Basic Earth attack. Hurls a heavy boulder at your target.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'earth',
    color: '#c9a56b',
    gradient: 'linear-gradient(135deg, #3E5151, #DECBA4)',
    icon: GiStonePile,
  },
  meteorShower: {
    id: 'meteorShower',
    name: 'Meteor Shower',
    description: 'Powerful Earth attack. A barrage of meteors strikes the target one after another, each impact dealing bonus damage to shields.',
    hotkey: 'W',
    kind: 'attack',
    element: 'earth',
    color: '#c9a56b',
    gradient: 'linear-gradient(135deg, #ba8b02, #181818)',
    icon: PiMeteorFill,
  },
  earthquake: {
    id: 'earthquake',
    name: 'Earthquake',
    description: 'Heavy Earth attack. Damages your target and sends aftershocks rippling into the kingdoms beside them.',
    hotkey: 'E',
    kind: 'attack',
    element: 'earth',
    color: '#c9a56b',
    gradient: 'linear-gradient(135deg, #42275a, #734b6d)',
    icon: RiEarthquakeFill,
  },
  naturalTerrain: {
    id: 'naturalTerrain',
    name: 'Natural Terrain',
    description: 'Blend in to the terrain around you — all incoming damage is halved for a while.',
    hotkey: 'R',
    kind: 'utility',
    element: 'earth',
    color: '#c9a56b',
    gradient: 'linear-gradient(135deg, #513B3C, #DECBA4)',
    icon: FaMountain,
  },
  brickWall: {
    id: 'brickWall',
    name: 'Brick Wall',
    description: 'Instantly raise a massive shield around your castle.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'earth',
    color: '#c9a56b',
    gradient: 'linear-gradient(135deg, #603813, #b29f94)',
    icon: GiDefensiveWall,
  },

  // Electricity Abilities
  zap: {
    id: 'zap',
    name: 'Zap',
    description: 'Basic Electricity attack. A quick spark on a very short cooldown.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'electricity',
    color: '#ffd24a',
    gradient: 'linear-gradient(135deg, #f9d423, #ff4e50)',
    icon: PiLightningFill,
  },
  lightningBarrage: {
    id: 'lightningBarrage',
    name: 'Lightning Barrage',
    description: 'Holds 3 Lightning charges. Spend 1, 2, or 3 at once — the more charges spent, the harder the bolts hit. Spent charges recharge on their own independent timers, so leftover charges can fire immediately.',
    hotkey: 'W',
    kind: 'attack',
    element: 'electricity',
    color: '#ffd24a',
    gradient: 'linear-gradient(135deg, #e1eec3, #f05053)',
    icon: GiLightningFlame,
    charges: true,
  },
  thunderdome: {
    id: 'thunderdome',
    name: 'Thunderdome',
    description: 'Combo attack that deals moderate damage and cages the target in a Thunderdome. While it stands, your Electricity attacks against them deal bonus damage.',
    hotkey: 'E',
    kind: 'attack',
    element: 'electricity',
    color: '#ffd24a',
    gradient: 'linear-gradient(135deg, #360033, #0b8793)',
    icon: GiLightningDome,
  },
  hack: {
    id: 'hack',
    name: 'Hack',
    description: 'Break into the target\'s vault and steal a share of their money and citizens. Deals no damage.',
    hotkey: 'R',
    kind: 'utility',
    element: 'electricity',
    color: '#ffd24a',
    gradient: 'linear-gradient(135deg, #000000, #53346d)',
    icon: TbDeviceLaptop,
  },
  thunderingFate: {
    id: 'thunderingFate',
    name: 'Thundering Fate',
    description: 'Overload your circuits — for a short window, Zap has no cooldown and costs a fraction of its usual price. Fire at will.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'electricity',
    color: '#ffd24a',
    gradient: 'linear-gradient(135deg, #f7ff00, #db36a4)',
    icon: GiThunderSkull,
  },

  // Ice Abilities
  icicle: {
    id: 'icicle',
    name: 'Icicle',
    description: 'Basic Ice attack. Fires a sharpened icicle at your target, dealing bonus damage if they are Frozen.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'ice',
    color: '#8fe3ff',
    gradient: 'linear-gradient(135deg, #1c92d2, #f2fcfe)',
    icon: RiSnowflakeFill,
  },
  floodOfFrost: {
    id: 'floodOfFrost',
    name: 'Flood of Frost',
    description: 'Powerful Ice attack with a chance to inflict Chilling Retribution, lengthening all of the target\'s cooldowns for a short time. Deals bonus damage to Frozen targets.',
    hotkey: 'W',
    kind: 'attack',
    element: 'ice',
    color: '#8fe3ff',
    gradient: 'linear-gradient(135deg, #36d1dc, #5b86e5)',
    icon: FaIcicles,
  },
  freezeToTheCore: {
    id: 'freezeToTheCore',
    name: 'Freeze to the Core',
    description: 'Freezes the target solid — guaranteed. Frozen kingdoms cannot attack for a few seconds, and take extra damage from your Ice attacks.',
    hotkey: 'E',
    kind: 'attack',
    element: 'ice',
    color: '#8fe3ff',
    gradient: 'linear-gradient(135deg, #00c6ff, #0072ff)',
    icon: GiMeltingIceCube,
  },
  snowman: {
    id: 'snowman',
    name: 'Snowman',
    description: 'Constructs an army of snowmen that boosts your income by 50% for 10 seconds.',
    hotkey: 'R',
    kind: 'utility',
    element: 'ice',
    color: '#8fe3ff',
    gradient: 'linear-gradient(135deg, #4facfe, #00f2fe)',
    icon: FaSnowman,
  },
  blizzard: {
    id: 'blizzard',
    name: 'Blizzard',
    description: 'A storm engulfs every opposing kingdom: they cannot attack and their production is frozen for several seconds.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'ice',
    color: '#8fe3ff',
    gradient: 'linear-gradient(135deg, #2193b0, #6dd5ed)',
    icon: GiSnowing,
  },

  // Nature Abilities
  sludge: {
    id: 'sludge',
    name: 'Sludge',
    description: 'Basic Nature attack coated in a weak Poison — a toxin that deals damage over time for a few seconds.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'nature',
    color: '#6bd88a',
    gradient: 'linear-gradient(135deg, #11998e, #38ef7d)',
    icon: PiBiohazardFill,
  },
  acidRain: {
    id: 'acidRain',
    name: 'Acid Rain',
    description: 'Moderate Nature attack that applies Corroded. While Corroded, the target takes increased Poison damage and your Poisons can stack on them.',
    hotkey: 'W',
    kind: 'attack',
    element: 'nature',
    color: '#6bd88a',
    gradient: 'linear-gradient(135deg, #a8ff78, #78ffd6)',
    icon: TbCloudRain,
  },
  gastroAcid: {
    id: 'gastroAcid',
    name: 'Gastro Acid',
    description: 'Powerful Nature attack that applies a strong Poison, with a chance to Poison the citizens too — poisoned citizens produce far less gold.',
    hotkey: 'E',
    kind: 'attack',
    element: 'nature',
    color: '#6bd88a',
    gradient: 'linear-gradient(135deg, #56ab2f, #a8ff78)',
    icon: PiSkullFill,
  },
  poisonApple: {
    id: 'poisonApple',
    name: 'Poison Apple',
    description: 'Leave out a tempting trap: the next kingdom to attack you bites the apple and is strongly Poisoned, taking damage over time.',
    hotkey: 'R',
    kind: 'utility',
    element: 'nature',
    color: '#6bd88a',
    gradient: 'linear-gradient(135deg, #ffe259, #ffa751)',
    icon: GiAppleCore,
  },
  toxicGas: {
    id: 'toxicGas',
    name: 'Toxic Gas',
    description: 'Envelop the target in a choking cloud of Toxic Gas — while it lingers, they cannot hire citizens or repair their castle.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'nature',
    color: '#6bd88a',
    gradient: 'linear-gradient(135deg, #00b4db, #0083b0)',
    icon: GiPoisonGas,
  },

  // Time Abilities (grandfather-clock theme: brown & beige)
  tikTok: {
    id: 'tikTok',
    name: 'Tik Tok',
    description: 'Basic Time attack. A steady tick-tock strike that never misses a beat.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'time',
    color: '#a9834e',
    gradient: 'linear-gradient(135deg, #3d2b1a, #7a5a34, #d9c39a)',
    icon: CiClock2,
  },
  halfPassed12: {
    id: 'halfPassed12',
    name: 'Half Passed 12',
    description: 'Devastating Time attack that scrambles the target\'s UI for 12 seconds.',
    hotkey: 'W',
    kind: 'attack',
    element: 'time',
    color: '#a9834e',
    gradient: 'linear-gradient(135deg, #5c4326, #a9834e)',
    icon: GiTimeSynchronization,
  },
  fatherTime: {
    id: 'fatherTime',
    name: 'Father Time',
    description: 'Heavy Time attack. Father Time hates wasting time: the victim takes damage each second they have not landed a damaging attack.',
    hotkey: 'E',
    kind: 'attack',
    element: 'time',
    color: '#a9834e',
    gradient: 'linear-gradient(135deg, #2e2013, #8b5a2b)',
    icon: LiaUserTimesSolid,
  },
  blip: {
    id: 'blip',
    name: 'Blip!',
    description: 'The most recent attack done to you is undone — including status effects and status-based damage.',
    hotkey: 'R',
    kind: 'utility',
    element: 'time',
    color: '#a9834e',
    gradient: 'linear-gradient(135deg, #7a5a34, #d9c39a)',
    icon: CgSandClock,
  },
  backToTheFuture: {
    id: 'backToTheFuture',
    name: 'Back to the Future',
    description: 'Rewind every castle\'s gold by 10 seconds',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'time',
    color: '#a9834e',
    gradient: 'linear-gradient(135deg, #3d2b1a, #b08d5a)',
    icon: RiRewindStartFill,
  },

  // Space Abilities (dark purple & black) — the bully. Three abilities feed a
  // shared Supernova meter that the heavy attack spends, hitting harder the more
  // it has charged.
  shootingStar: {
    id: 'shootingStar',
    name: 'Shooting Star',
    description: 'Basic Space attack. Hurls a shooting star at your target and trickles charge into your Supernova.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'space',
    color: '#5b21b6',
    gradient: 'linear-gradient(135deg, #0a0518, #4b2fae, #5b21b6)',
    icon: GiFallingStar,
  },
  saturnsRings: {
    id: 'saturnsRings',
    name: "Saturn's Rings",
    description: 'Bombards a single kingdom with a relentless barrage of 9 planetary rings. Every ring that lands charges your Supernova.',
    hotkey: 'W',
    kind: 'attack',
    element: 'space',
    color: '#5b21b6',
    gradient: 'linear-gradient(135deg, #0a0518, #4a1a9e)',
    icon: SiSaturn,
  },
  supernova: {
    id: 'supernova',
    name: 'Supernova',
    description: 'Unleashes your Supernova at its CURRENT charge — you can’t pick the level. Higher charge means far more damage and, once charged enough, hijacks the whole field onto your victim. Empties the meter.',
    hotkey: 'E',
    kind: 'attack',
    element: 'space',
    color: '#5b21b6',
    gradient: 'linear-gradient(135deg, #1a0033, #7a1fd6, #d94bff)',
    icon: TbBrandSupernova,
  },
  orionsBeltAbility: {
    id: 'orionsBeltAbility',
    name: "Orion's Belt",
    description: 'Surrounds you with a celestial ring of orbiting asteroids: incoming attacks have a 50% chance to miss for 10s, and every miss charges your Supernova.',
    hotkey: 'R',
    kind: 'utility',
    element: 'space',
    color: '#5b21b6',
    gradient: 'linear-gradient(135deg, #0a0518, #3a2a7e, #5b21b6)',
    icon: GiStoneSphere,
  },
  blackHole: {
    id: 'blackHole',
    name: 'Black Hole',
    description: 'Ultimate. Opens a black hole that swallows every attack on the field for 10s, then dumps all of it on the last kingdom that fed it.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'space',
    color: '#5b21b6',
    gradient: 'linear-gradient(135deg, #000000, #2a1a5e)',
    icon: GiBlackHoleBolas,
  },

  // Love Abilities (rose pink & blush) — a social, manipulative kit: it
  // borrows resources, redirects damage, and ties enemy fates together.
  toughLove: {
    id: 'toughLove',
    name: 'Tough Love',
    description: 'Basic Love attack. A firm, caring smack to get the point across.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'love',
    color: '#ff4d8d',
    gradient: 'linear-gradient(135deg, #5c1030, #b8265c, #ff4d8d)',
    icon: FaHeart,
  },
  cupidsArrow: {
    id: 'cupidsArrow',
    name: "Cupid's Arrow",
    description: 'Moderate damage that marks the target "infatuated": they lend you citizens and feel a share of whatever damage you take, for a while.',
    hotkey: 'W',
    kind: 'attack',
    element: 'love',
    color: '#ff4d8d',
    gradient: 'linear-gradient(135deg, #ff4d8d, #ffd1e3)',
    icon: BsArrowThroughHeartFill,
  },
  bffs: {
    id: 'bffs',
    name: 'BFFS!!!',
    description: 'Deals damage to your target and a second, random enemy, then links their fates: damage and status effects hitting either one hit both.',
    hotkey: 'E',
    kind: 'attack',
    element: 'love',
    color: '#ff4d8d',
    gradient: 'linear-gradient(135deg, #b8265c, #ff4d8d, #ffb3cf)',
    icon: BsEmojiHeartEyesFill,
  },
  empathy: {
    id: 'empathy',
    name: 'Have some Empathy!',
    description: 'For a while, any damage you take is felt right back by the attacker, in full.',
    hotkey: 'R',
    kind: 'utility',
    element: 'love',
    color: '#ff4d8d',
    gradient: 'linear-gradient(135deg, #5c1030, #ff4d8d)',
    icon: GiLoveInjection,
  },
  loveGalore: {
    id: 'loveGalore',
    name: 'Love Galore',
    description: 'Ultimate. Incoming damage never lands — it secretly heals you for half instead. Attackers see normal damage until it reveals (after 15s or 1500 healing), then all damage openly becomes healing for another 15s.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'love',
    color: '#ff4d8d',
    gradient: 'linear-gradient(135deg, #ff4d8d, #ff85ac, #ffd1e3)',
    icon: GiChainedHeart,
  },
  // Joker Abilities — PLACEHOLDER (see Server/src/data/jokerAbilities.ts)
  jokerAbility1: {
    id: 'jokerAbility1',
    name: 'JokerAbility1',
    description: 'Placeholder attack — a plain damaging cast standing in until the real Joker kit is designed.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'joker',
    color: '#e02434',
    gradient: 'linear-gradient(135deg, #5e0a13, #e02434, #f7f7f2)',
    icon: GiCardJoker,
  },
  jokerAbility2: {
    id: 'jokerAbility2',
    name: 'JokerAbility2',
    description: 'Placeholder attack — a plain damaging cast standing in until the real Joker kit is designed.',
    hotkey: 'E',
    kind: 'attack',
    element: 'joker',
    color: '#e02434',
    gradient: 'linear-gradient(135deg, #5e0a13, #e02434, #f7f7f2)',
    icon: GiJesterHat,
  },
  jokerAbility3: {
    id: 'jokerAbility3',
    name: 'JokerAbility3',
    description: 'Placeholder attack — a plain damaging cast standing in until the real Joker kit is designed.',
    hotkey: 'F',
    kind: 'attack',
    element: 'joker',
    color: '#e02434',
    gradient: 'linear-gradient(135deg, #5e0a13, #e02434, #f7f7f2)',
    icon: GiTopHat,
  },
  jokerAbility4: {
    id: 'jokerAbility4',
    name: 'JokerAbility4',
    description: 'Placeholder utility — a short self buff standing in until the real Joker kit is designed.',
    hotkey: 'R',
    kind: 'utility',
    element: 'joker',
    color: '#e02434',
    gradient: 'linear-gradient(135deg, #5e0a13, #e02434, #f7f7f2)',
    icon: GiBalloons,
  },
  jokerAbility5: {
    id: 'jokerAbility5',
    name: 'JokerAbility5',
    description: 'Placeholder ultimate — one heavy hit standing in until the real Joker kit is designed.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'joker',
    color: '#e02434',
    gradient: 'linear-gradient(135deg, #5e0a13, #e02434, #f7f7f2)',
    icon: GiClown,
  },
  // Light Abilities — PLACEHOLDER (see Server/src/data/lightAbilities.ts)
  lightAbility1: {
    id: 'lightAbility1',
    name: 'LightAbility1',
    description: 'Placeholder attack — a plain damaging cast standing in until the real Light kit is designed.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'light',
    color: '#f7f7f2',
    gradient: 'linear-gradient(135deg, #9a9a93, #f7f7f2)',
    icon: GiSunbeams,
  },
  lightAbility2: {
    id: 'lightAbility2',
    name: 'LightAbility2',
    description: 'Placeholder attack — a plain damaging cast standing in until the real Light kit is designed.',
    hotkey: 'E',
    kind: 'attack',
    element: 'light',
    color: '#f7f7f2',
    gradient: 'linear-gradient(135deg, #9a9a93, #f7f7f2)',
    icon: GiSunrise,
  },
  lightAbility3: {
    id: 'lightAbility3',
    name: 'LightAbility3',
    description: 'Placeholder attack — a plain damaging cast standing in until the real Light kit is designed.',
    hotkey: 'F',
    kind: 'attack',
    element: 'light',
    color: '#f7f7f2',
    gradient: 'linear-gradient(135deg, #9a9a93, #f7f7f2)',
    icon: GiSunRadiations,
  },
  lightAbility4: {
    id: 'lightAbility4',
    name: 'LightAbility4',
    description: 'Placeholder utility — a short self buff standing in until the real Light kit is designed.',
    hotkey: 'R',
    kind: 'utility',
    element: 'light',
    color: '#f7f7f2',
    gradient: 'linear-gradient(135deg, #9a9a93, #f7f7f2)',
    icon: GiCandleLight,
  },
  lightAbility5: {
    id: 'lightAbility5',
    name: 'LightAbility5',
    description: 'Placeholder ultimate — one heavy hit standing in until the real Light kit is designed.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'light',
    color: '#f7f7f2',
    gradient: 'linear-gradient(135deg, #9a9a93, #f7f7f2)',
    icon: GiHolyGrail,
  },
  // Dark Abilities — PLACEHOLDER (see Server/src/data/darkAbilities.ts)
  darkAbility1: {
    id: 'darkAbility1',
    name: 'DarkAbility1',
    description: 'Placeholder attack — a plain damaging cast standing in until the real Dark kit is designed.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'dark',
    color: '#12121a',
    gradient: 'linear-gradient(135deg, #050508, #12121a, #f7f7f2)',
    icon: GiNightSky,
  },
  darkAbility2: {
    id: 'darkAbility2',
    name: 'DarkAbility2',
    description: 'Placeholder attack — a plain damaging cast standing in until the real Dark kit is designed.',
    hotkey: 'E',
    kind: 'attack',
    element: 'dark',
    color: '#12121a',
    gradient: 'linear-gradient(135deg, #050508, #12121a, #f7f7f2)',
    icon: GiRaven,
  },
  darkAbility3: {
    id: 'darkAbility3',
    name: 'DarkAbility3',
    description: 'Placeholder attack — a plain damaging cast standing in until the real Dark kit is designed.',
    hotkey: 'F',
    kind: 'attack',
    element: 'dark',
    color: '#12121a',
    gradient: 'linear-gradient(135deg, #050508, #12121a, #f7f7f2)',
    icon: GiMoonBats,
  },
  darkAbility4: {
    id: 'darkAbility4',
    name: 'DarkAbility4',
    description: 'Placeholder utility — a short self buff standing in until the real Dark kit is designed.',
    hotkey: 'R',
    kind: 'utility',
    element: 'dark',
    color: '#12121a',
    gradient: 'linear-gradient(135deg, #050508, #12121a, #f7f7f2)',
    icon: GiShadowFollower,
  },
  darkAbility5: {
    id: 'darkAbility5',
    name: 'DarkAbility5',
    description: 'Placeholder ultimate — one heavy hit standing in until the real Dark kit is designed.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'dark',
    color: '#12121a',
    gradient: 'linear-gradient(135deg, #050508, #12121a, #f7f7f2)',
    icon: GiEclipse,
  },
}

export function getAbilitiesForKingdom(kingdomId: string | null): ClientAbilityMetadata[] {
  if (!kingdomId) return []
  return Object.values(ABILITY_METADATA).filter((m) => m.element === kingdomId)
}
