import type { IconType } from 'react-icons'
import { PiDropFill, PiFireFill, PiWindFill, PiEyeFill, PiMeteorFill, PiLightningFill, PiBiohazardFill, PiSkullFill } from 'react-icons/pi'
import { BsWater, BsArrowThroughHeartFill, BsEmojiHeartEyesFill } from 'react-icons/bs'
import { MdFlood } from 'react-icons/md'
import { FaSun, FaIcicles, FaMountain, FaSnowman, FaHeart, FaLightbulb, FaYinYang } from 'react-icons/fa'
import { FaBottleWater, FaHurricane } from 'react-icons/fa6'
import { GiWaveSurfer, GiFireDash, GiStonePile, GiDefensiveWall, GiLightningFlame, GiLightningDome, GiThunderSkull, GiMeltingIceCube, GiSnowing, GiAppleCore, GiPoisonGas, GiTimeSynchronization, GiBlackHoleBolas, GiFallingStar, GiStoneSphere, GiLoveInjection, GiChainedHeart } from 'react-icons/gi'
import { TbTornado, TbTemperatureMinusFilled, TbDeviceLaptop, TbCloudRain, TbBrandSupernova, TbRoulette } from 'react-icons/tb'
import { WiFog } from 'react-icons/wi'
import { SiBunnydotnet, SiSaturn } from 'react-icons/si'
import { RiEarthquakeFill, RiSnowflakeFill, RiRewindStartFill } from 'react-icons/ri'
import { CiClock2 } from 'react-icons/ci'
import { CgSandClock } from 'react-icons/cg'
import { LiaUserTimesSolid } from 'react-icons/lia'
import { LuReceiptJapaneseYen } from 'react-icons/lu'
import { FaSmog } from 'react-icons/fa'
import { GiInsectJaws, GiHangingSpider, GiButterflyFlower, GiEruption, GiPunchBlast, GiLava, GiSmokingVolcano, GiFire, GiFox, GiFoxHead, GiFoxTail, GiFlashGrenade, GiLighthouse, GiCardAceSpades, GiCardExchange, GiCardRandom, GiRollingDices, GiEvilLove, GiDreamCatcher, GiDelighted } from 'react-icons/gi'
import { IoFlashlight } from 'react-icons/io5'
import { PiBugDroid, PiButterflyFill } from 'react-icons/pi'
import { BsShadows } from 'react-icons/bs'
import { BiBug } from 'react-icons/bi'

export interface ClientAbilityMetadata {
  id: string
  name: string
  description: string
  hotkey: string
  kind: 'attack' | 'utility' | 'ultimate' | 'passive'
  element: string
  color: string // theme color hex
  gradient: string // CSS gradient for buttons
  icon: IconType // react-icons component rendered on the ability card
  /**
   * Charge-based casts (Lightning Barrage): the card shows mini cast buttons
   * for spending 1/2/3 charges. This flag only says the ability HAS charges —
   * the pool size, per-charge price, damage table, and regen cadence are all
   * server-derived (`GamePlayer.abilityPrices[id].charges`).
   */
  charges?: true
  /**
   * The cast must name one of these (Dark's Yin and Yang). The card renders a
   * small button per option instead of a single cast button; the pick is sent
   * as `choice` and validated server-side against the same list.
   */
  choices?: readonly { value: string; label: string; hint: string }[]
}

export const ABILITY_METADATA: Record<string, ClientAbilityMetadata> = {
  // Water Abilities
  waterBall: {
    id: 'waterBall',
    name: 'Water Ball',
    description: 'Basic Water attack. Hurls a sphere of compressed water at your target.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'water',
    color: '#4aa3ff',
    gradient: 'linear-gradient(135deg, #1e3c72, #2a5298, #4aa3ff)',
    icon: PiDropFill,
  },
  waterfall: {
    id: 'waterfall',
    name: 'Waterfall',
    description: 'Powerful Water attack that applies Current. While caught in a Current, your Water attacks heal your castle based on damage dealt, and Flood lasts longer against them.',
    hotkey: 'W',
    kind: 'attack',
    element: 'water',
    color: '#4aa3ff',
    gradient: 'linear-gradient(135deg, #2b5876, #4e4376, #4aa3ff)',
    icon: BsWater,
  },
  flood: {
    id: 'flood',
    name: 'Flood',
    description: ' Washes over the target, preventing them from targeting you for a few seconds — even longer if they are caught in a Current.',
    hotkey: 'E',
    kind: 'attack',
    element: 'water',
    color: '#4aa3ff',
    gradient: 'linear-gradient(135deg, #0f2027, #203a43, #2c5364)',
    icon: MdFlood,
  },
  fluidAssimilation: {
    id: 'fluidAssimilation',
    name: 'Fluid Assimilation',
    description: 'Dissolve into the surrounding moisture: no enemy can attack you for 5 seconds.',
    hotkey: 'R',
    kind: 'utility',
    element: 'water',
    color: '#4aa3ff',
    gradient: 'linear-gradient(135deg, #2193b0, #6dd5ed)',
    icon: FaBottleWater,
  },
  riptide: {
    id: 'riptide',
    name: 'Riptide',
    description: 'The tide turns in your favor: restore half your castle health and draw new citizens to your banner.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'water',
    color: '#4aa3ff',
    gradient: 'linear-gradient(135deg, #00c6ff, #0072ff)',
    icon: GiWaveSurfer,
  },

  // Fire Abilities
  fireball: {
    id: 'fireball',
    name: 'Fireball',
    description: 'Basic Fire attack. Launches a searing fireball at your target.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'fire',
    color: '#ff6b4a',
    gradient: 'linear-gradient(135deg, #870000, #190000, #ff6b4a)',
    icon: PiFireFill,
  },
  scorchingSun: {
    id: 'scorchingSun',
    name: 'Scorching Sun',
    description: 'Powerful Fire attack that leaves the target IGNITED for a minute. Ignited does no damage on its own — every 15 seconds it rolls a 25% chance to set a real Burn, so they never know when the fire is coming.',
    hotkey: 'W',
    kind: 'attack',
    element: 'fire',
    color: '#ff6b4a',
    gradient: 'linear-gradient(135deg, #f12711, #f5af19)',
    icon: FaSun,
  },
  firenado: {
    id: 'firenado',
    name: 'Firenado',
    description: 'Very powerful Fire attack that ALWAYS burns. Hits significantly harder against a target that is Ignited but not yet burning — set them alight with Scorching Sun first, then cash it in.',
    hotkey: 'E',
    kind: 'attack',
    element: 'fire',
    color: '#ff6b4a',
    gradient: 'linear-gradient(135deg, #f857a6, #ff5858)',
    icon: TbTornado,
  },
  heatWave: {
    id: 'heatWave',
    name: 'Heat Wave',
    description: 'Superheat the air around your castle, temporarily raising your critical hit chance and critical damage. Cannot stack.',
    hotkey: 'R',
    kind: 'utility',
    element: 'fire',
    color: '#ff6b4a',
    gradient: 'linear-gradient(135deg, #ff9966, #ff5e62)',
    icon: TbTemperatureMinusFilled,
  },
  blazingDetermination: {
    id: 'blazingDetermination',
    name: 'Blazing Determination',
    description: 'Pour everything into a single strike — your next attack deals massively increased damage.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'fire',
    color: '#ff6b4a',
    gradient: 'linear-gradient(135deg, #e52d27, #b31217)',
    icon: GiFireDash,
  },

  // Air Abilities
  aLightBreeze: {
    id: 'aLightBreeze',
    name: 'A Light Breeze',
    description: 'Basic Air attack. Slices the target with compressed wind currents. While Bird\'s Eye View is active, the attacks have a chance to bounce between kingdoms.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'air',
    color: '#b7c9ff',
    gradient: 'linear-gradient(135deg, #4b6cb7, #182848)',
    icon: PiWindFill,
  },
  hurricane: {
    id: 'hurricane',
    name: 'Hurricane',
    description: 'Powerful Air attack. The next time the victim attacks you, their attack is guaranteed to be deflected into another kingdom instead.',
    hotkey: 'W',
    kind: 'attack',
    element: 'air',
    color: '#b7c9ff',
    gradient: 'linear-gradient(135deg, #83a4d4, #b6fbff)',
    icon: FaHurricane,
  },
  thickFog: {
    id: 'thickFog',
    name: 'Thick Fog',
    description: 'Moderate Air attack that blankets the target\'s screen in fog, hiding battlefield information from them for a short time.',
    hotkey: 'E',
    kind: 'attack',
    element: 'air',
    color: '#b7c9ff',
    gradient: 'linear-gradient(135deg, #6190e8, #a7bfe8)',
    icon: WiFog,
  },
  birdsEyeView: {
    id: 'birdsEyeView',
    name: "Bird's Eye View",
    description: 'Rise above the clouds to temporarily reveal every kingdom\'s castle HP, shields, citizens, and income.',
    hotkey: 'R',
    kind: 'utility',
    element: 'air',
    color: '#b7c9ff',
    gradient: 'linear-gradient(135deg, #2b5876, #4e4376)',
    icon: PiEyeFill,
  },
  dustBunnies: {
    id: 'dustBunnies',
    name: 'Dust Bunnies',
    description: 'Send dust bunnies scurrying into every opposing kingdom, slowly gnawing away at them with damage over time.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'air',
    color: '#b7c9ff',
    gradient: 'linear-gradient(135deg, #3a7bd5, #3a6073)',
    icon: SiBunnydotnet,
  },

  // Earth Abilities
  rockThrow: {
    id: 'rockThrow',
    name: 'Rock Throw',
    description: 'Basic Earth attack. Hurls a heavy boulder at your target.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'earth',
    color: '#c9a56b',
    gradient: 'linear-gradient(135deg, #3E5151, #DECBA4)',
    icon: GiStonePile,
  },
  meteorShower: {
    id: 'meteorShower',
    name: 'Meteor Shower',
    description: 'Powerful Earth attack. A barrage of meteors strikes the target one after another, each impact dealing bonus damage to shields.',
    hotkey: 'W',
    kind: 'attack',
    element: 'earth',
    color: '#c9a56b',
    gradient: 'linear-gradient(135deg, #ba8b02, #181818)',
    icon: PiMeteorFill,
  },
  earthquake: {
    id: 'earthquake',
    name: 'Earthquake',
    description: 'Heavy Earth attack. Damages your target and sends aftershocks rippling into the kingdoms beside them.',
    hotkey: 'E',
    kind: 'attack',
    element: 'earth',
    color: '#c9a56b',
    gradient: 'linear-gradient(135deg, #42275a, #734b6d)',
    icon: RiEarthquakeFill,
  },
  naturalTerrain: {
    id: 'naturalTerrain',
    name: 'Natural Terrain',
    description: 'Blend in to the terrain around you — all incoming damage is halved for a while.',
    hotkey: 'R',
    kind: 'utility',
    element: 'earth',
    color: '#c9a56b',
    gradient: 'linear-gradient(135deg, #513B3C, #DECBA4)',
    icon: FaMountain,
  },
  brickWall: {
    id: 'brickWall',
    name: 'Brick Wall',
    description: 'Instantly raise a massive shield around your castle.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'earth',
    color: '#c9a56b',
    gradient: 'linear-gradient(135deg, #603813, #b29f94)',
    icon: GiDefensiveWall,
  },

  // Electricity Abilities
  zap: {
    id: 'zap',
    name: 'Zap',
    description: 'Basic Electricity attack. A quick spark on a very short cooldown.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'electricity',
    color: '#ffd24a',
    gradient: 'linear-gradient(135deg, #f9d423, #ff4e50)',
    icon: PiLightningFill,
  },
  lightningBarrage: {
    id: 'lightningBarrage',
    name: 'Lightning Barrage',
    description: 'Holds 3 Lightning charges. Spend 1, 2, or 3 at once — the more charges spent, the harder the bolts hit. Spent charges recharge on their own independent timers, so leftover charges can fire immediately.',
    hotkey: 'W',
    kind: 'attack',
    element: 'electricity',
    color: '#ffd24a',
    gradient: 'linear-gradient(135deg, #e1eec3, #f05053)',
    icon: GiLightningFlame,
    charges: true,
  },
  thunderdome: {
    id: 'thunderdome',
    name: 'Thunderdome',
    description: 'Combo attack that deals moderate damage and cages the target in a Thunderdome. While it stands, your Electricity attacks against them deal bonus damage.',
    hotkey: 'E',
    kind: 'attack',
    element: 'electricity',
    color: '#ffd24a',
    gradient: 'linear-gradient(135deg, #360033, #0b8793)',
    icon: GiLightningDome,
  },
  hack: {
    id: 'hack',
    name: 'Hack',
    description: 'Break into the target\'s vault and steal a share of their money and citizens. Deals no damage.',
    hotkey: 'R',
    kind: 'utility',
    element: 'electricity',
    color: '#ffd24a',
    gradient: 'linear-gradient(135deg, #000000, #53346d)',
    icon: TbDeviceLaptop,
  },
  thunderingFate: {
    id: 'thunderingFate',
    name: 'Thundering Fate',
    description: 'Overload your circuits — for a short window, Zap has no cooldown and costs a fraction of its usual price. Fire at will.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'electricity',
    color: '#ffd24a',
    gradient: 'linear-gradient(135deg, #f7ff00, #db36a4)',
    icon: GiThunderSkull,
  },

  // Ice Abilities
  icicle: {
    id: 'icicle',
    name: 'Icicle',
    description: 'Basic Ice attack. Fires a sharpened icicle at your target, dealing bonus damage if they are Frozen.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'ice',
    color: '#8fe3ff',
    gradient: 'linear-gradient(135deg, #1c92d2, #f2fcfe)',
    icon: RiSnowflakeFill,
  },
  floodOfFrost: {
    id: 'floodOfFrost',
    name: 'Flood of Frost',
    description: 'Powerful Ice attack with a chance to inflict Chilling Retribution, lengthening all of the target\'s cooldowns for a short time. Deals bonus damage to Frozen targets.',
    hotkey: 'W',
    kind: 'attack',
    element: 'ice',
    color: '#8fe3ff',
    gradient: 'linear-gradient(135deg, #36d1dc, #5b86e5)',
    icon: FaIcicles,
  },
  freezeToTheCore: {
    id: 'freezeToTheCore',
    name: 'Freeze to the Core',
    description: 'Freezes the target solid — guaranteed. Frozen kingdoms cannot attack for a few seconds, and take extra damage from your Ice attacks.',
    hotkey: 'E',
    kind: 'attack',
    element: 'ice',
    color: '#8fe3ff',
    gradient: 'linear-gradient(135deg, #00c6ff, #0072ff)',
    icon: GiMeltingIceCube,
  },
  snowman: {
    id: 'snowman',
    name: 'Snowman',
    description: 'Constructs an army of snowmen that boosts your income by 50% for 10 seconds.',
    hotkey: 'R',
    kind: 'utility',
    element: 'ice',
    color: '#8fe3ff',
    gradient: 'linear-gradient(135deg, #4facfe, #00f2fe)',
    icon: FaSnowman,
  },
  blizzard: {
    id: 'blizzard',
    name: 'Blizzard',
    description: 'A storm engulfs every opposing kingdom: they cannot attack and their production is frozen for several seconds.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'ice',
    color: '#8fe3ff',
    gradient: 'linear-gradient(135deg, #2193b0, #6dd5ed)',
    icon: GiSnowing,
  },

  // Nature Abilities
  sludge: {
    id: 'sludge',
    name: 'Sludge',
    description: 'Basic Nature attack coated in a weak Poison — a toxin that deals damage over time for a few seconds.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'nature',
    color: '#6bd88a',
    gradient: 'linear-gradient(135deg, #11998e, #38ef7d)',
    icon: PiBiohazardFill,
  },
  acidRain: {
    id: 'acidRain',
    name: 'Acid Rain',
    description: 'Moderate Nature attack that applies Corroded. While Corroded, the target takes increased Poison damage and your Poisons can stack on them.',
    hotkey: 'W',
    kind: 'attack',
    element: 'nature',
    color: '#6bd88a',
    gradient: 'linear-gradient(135deg, #a8ff78, #78ffd6)',
    icon: TbCloudRain,
  },
  gastroAcid: {
    id: 'gastroAcid',
    name: 'Gastro Acid',
    description: 'Powerful Nature attack that applies a strong Poison, with a chance to Poison the citizens too — poisoned citizens produce far less gold.',
    hotkey: 'E',
    kind: 'attack',
    element: 'nature',
    color: '#6bd88a',
    gradient: 'linear-gradient(135deg, #56ab2f, #a8ff78)',
    icon: PiSkullFill,
  },
  poisonApple: {
    id: 'poisonApple',
    name: 'Poison Apple',
    description: 'Leave out a tempting trap: the next kingdom to attack you bites the apple and is strongly Poisoned, taking damage over time.',
    hotkey: 'R',
    kind: 'utility',
    element: 'nature',
    color: '#6bd88a',
    gradient: 'linear-gradient(135deg, #ffe259, #ffa751)',
    icon: GiAppleCore,
  },
  toxicGas: {
    id: 'toxicGas',
    name: 'Toxic Gas',
    description: 'Envelop all players in a choking cloud of Toxic Gas — while it lingers, they cannot hire citizens or repair their castle.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'nature',
    color: '#6bd88a',
    gradient: 'linear-gradient(135deg, #00b4db, #0083b0)',
    icon: GiPoisonGas,
  },

  // Time Abilities (grandfather-clock theme: brown & beige)
  tikTok: {
    id: 'tikTok',
    name: 'Tik Tok',
    description: 'Basic Time attack. A steady tick-tock strike that never misses a beat.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'time',
    color: '#a9834e',
    gradient: 'linear-gradient(135deg, #3d2b1a, #7a5a34, #d9c39a)',
    icon: CiClock2,
  },
  halfPassed12: {
    id: 'halfPassed12',
    name: 'Half Passed 12',
    description: 'Devastating Time attack that scrambles the target\'s UI for 12 seconds.',
    hotkey: 'W',
    kind: 'attack',
    element: 'time',
    color: '#a9834e',
    gradient: 'linear-gradient(135deg, #5c4326, #a9834e)',
    icon: GiTimeSynchronization,
  },
  fatherTime: {
    id: 'fatherTime',
    name: 'Father Time',
    description: 'Father Time hates wasting time: the victim takes damage each second they have not landed a damaging attack.',
    hotkey: 'E',
    kind: 'attack',
    element: 'time',
    color: '#a9834e',
    gradient: 'linear-gradient(135deg, #2e2013, #8b5a2b)',
    icon: LiaUserTimesSolid,
  },
  blip: {
    id: 'blip',
    name: 'Blip!',
    description: 'The most recent attack done to you is undone — including status effects and status-based damage.',
    hotkey: 'R',
    kind: 'utility',
    element: 'time',
    color: '#a9834e',
    gradient: 'linear-gradient(135deg, #7a5a34, #d9c39a)',
    icon: CgSandClock,
  },
  backToTheFuture: {
    id: 'backToTheFuture',
    name: 'Back to the Future',
    description: 'Rewind every castle\'s gold by 10 seconds',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'time',
    color: '#a9834e',
    gradient: 'linear-gradient(135deg, #3d2b1a, #b08d5a)',
    icon: RiRewindStartFill,
  },

  // Space Abilities (dark purple & black) — the bully. Three abilities feed a
  // shared Supernova meter that the heavy attack spends, hitting harder the more
  // it has charged.
  shootingStar: {
    id: 'shootingStar',
    name: 'Shooting Star',
    description: 'Basic Space attack. Hurls a shooting star at your target and trickles charge into your Supernova.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'space',
    color: '#5b21b6',
    gradient: 'linear-gradient(135deg, #0a0518, #4b2fae, #5b21b6)',
    icon: GiFallingStar,
  },
  saturnsRings: {
    id: 'saturnsRings',
    name: "Saturn's Rings",
    description: 'Bombards a single kingdom with a relentless barrage of 9 planetary rings. Every ring that lands charges your Supernova.',
    hotkey: 'W',
    kind: 'attack',
    element: 'space',
    color: '#5b21b6',
    gradient: 'linear-gradient(135deg, #0a0518, #4a1a9e)',
    icon: SiSaturn,
  },
  supernova: {
    id: 'supernova',
    name: 'Supernova',
    description: 'Unleashes your Supernova at its CURRENT charge — you can’t pick the level. Higher charge means far more damage and, once charged enough, hijacks the whole field onto your victim. Empties the meter.',
    hotkey: 'E',
    kind: 'attack',
    element: 'space',
    color: '#5b21b6',
    gradient: 'linear-gradient(135deg, #1a0033, #7a1fd6, #d94bff)',
    icon: TbBrandSupernova,
  },
  orionsBeltAbility: {
    id: 'orionsBeltAbility',
    name: "Orion's Belt",
    description: 'Surrounds you with a celestial ring of orbiting asteroids: incoming attacks have a 50% chance to miss for 10s, and every miss charges your Supernova.',
    hotkey: 'R',
    kind: 'utility',
    element: 'space',
    color: '#5b21b6',
    gradient: 'linear-gradient(135deg, #0a0518, #3a2a7e, #5b21b6)',
    icon: GiStoneSphere,
  },
  blackHole: {
    id: 'blackHole',
    name: 'Black Hole',
    description: 'Ultimate. Opens a black hole that swallows every attack on the field for 10s, then dumps all of it on the last kingdom that fed it.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'space',
    color: '#5b21b6',
    gradient: 'linear-gradient(135deg, #000000, #2a1a5e)',
    icon: GiBlackHoleBolas,
  },

  // Love Abilities (rose pink & blush) — a social, manipulative kit: it
  // borrows resources, redirects damage, and ties enemy fates together.
  toughLove: {
    id: 'toughLove',
    name: 'Tough Love',
    description: 'Basic Love attack. Love hurts.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'love',
    color: '#ff4d8d',
    gradient: 'linear-gradient(135deg, #5c1030, #b8265c, #ff4d8d)',
    icon: FaHeart,
  },
  cupidsArrow: {
    id: 'cupidsArrow',
    name: "Cupid's Arrow",
    description: 'Moderate damage that marks the target "infatuated": they lend you citizens and feel a share of whatever damage you take, for a while.',
    hotkey: 'W',
    kind: 'attack',
    element: 'love',
    color: '#ff4d8d',
    gradient: 'linear-gradient(135deg, #ff4d8d, #ffd1e3)',
    icon: BsArrowThroughHeartFill,
  },
  bffs: {
    id: 'bffs',
    name: 'BFFS!!!',
    description: 'Choose two targets and link them together: damage and status effects hitting either one hit both.',
    hotkey: 'E',
    kind: 'attack',
    element: 'love',
    color: '#ff4d8d',
    gradient: 'linear-gradient(135deg, #b8265c, #ff4d8d, #ffb3cf)',
    icon: BsEmojiHeartEyesFill,
  },
  empathy: {
    id: 'empathy',
    name: 'Have some Empathy!',
    description: 'For a while, any damage you take is felt right back by the attacker, in full.',
    hotkey: 'R',
    kind: 'utility',
    element: 'love',
    color: '#ff4d8d',
    gradient: 'linear-gradient(135deg, #5c1030, #ff4d8d)',
    icon: GiLoveInjection,
  },
  loveGalore: {
    id: 'loveGalore',
    name: 'Love Galore',
    description: 'Ultimate. Incoming damage never lands — it secretly heals you for half instead. Attackers see normal damage until it reveals (after 15s or 1500 healing), then all damage openly becomes healing for another 15s.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'love',
    color: '#ff4d8d',
    gradient: 'linear-gradient(135deg, #ff4d8d, #ff85ac, #ffd1e3)',
    icon: GiChainedHeart,
  },
  // Joker Abilities — PLACEHOLDER (see Server/src/data/jokerAbilities.ts)
  aceOfSpades: {
    id: 'aceOfSpades',
    name: 'Ace of Spades',
    description: 'Basic Joker attack. Also pulls every 2 and 3 out of your Blackjack deck for 5 seconds',
    hotkey: 'Q',
    kind: 'attack',
    element: 'joker',
    color: '#e02434',
    gradient: 'linear-gradient(135deg, #5e0a13, #e02434, #f7f7f2)',
    icon: GiCardAceSpades,
  },
  blackjack: {
    id: 'blackjack',
    name: 'Blackjack',
    description: 'Draws one card from a full 52-card deck and hits for what it is worth, the higher the number, the bigger the damage.',
    hotkey: 'E',
    kind: 'attack',
    element: 'joker',
    color: '#e02434',
    gradient: 'linear-gradient(135deg, #5e0a13, #e02434, #f7f7f2)',
    icon: GiCardExchange,
  },
  roulette: {
    id: 'roulette',
    name: 'Roulette',
    description: 'Force a kingdom to play a game of Roulette. Takes half damage on a win and full damage on a loss. Betting on green grants them healing on a win but extra damage on a loss',
    hotkey: 'F',
    kind: 'attack',
    element: 'joker',
    color: '#e02434',
    gradient: 'linear-gradient(135deg, #5e0a13, #e02434, #f7f7f2)',
    icon: TbRoulette,
  },
  luckyDraw: {
    id: 'luckyDraw',
    name: 'Lucky Draw',
    description: 'Take a card, any card. One of five effects is randomly applied to your castle',
    hotkey: 'R',
    kind: 'utility',
    element: 'joker',
    color: '#e02434',
    gradient: 'linear-gradient(135deg, #5e0a13, #e02434, #f7f7f2)',
    icon: GiCardRandom,
  },
  slotMachine: {
    id: 'slotMachine',
    name: 'Slot Machine',
    description: 'Drops a slot machine on every other kingdom. Their gold production stops until they pull the lever — and then the reels decide what happens to them.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'joker',
    color: '#e02434',
    gradient: 'linear-gradient(135deg, #5e0a13, #e02434, #f7f7f2)',
    icon: GiRollingDices,
  },
  // Light Abilities — attacks designed; utility + ultimate still placeholders
  // (see Server/src/data/lightAbilities.ts).
  lightBeam: {
    id: 'lightBeam',
    name: 'Light Beam',
    description: 'Basic Light attack. A focused beam of pure light — and it burns hotter against a kingdom already crawling with your Fireflies.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'light',
    color: '#f7f7f2',
    gradient: 'linear-gradient(135deg, #9a9a93, #f7f7f2)',
    icon: IoFlashlight,
  },
  fireflies: {
    id: 'fireflies',
    name: 'Fireflies',
    description: 'Sends a swarm to infest an enemy castle. They must pay to shoo it away but a shielded castle repels the swarm entirely. While swarmed, the opposing castle cannot purchase a shield.',
    hotkey: 'E',
    kind: 'attack',
    element: 'light',
    color: '#f7f7f2',
    gradient: 'linear-gradient(135deg, #9a9a93, #f7f7f2)',
    icon: PiBugDroid,
  },
  illumination: {
    id: 'illumination',
    name: 'Illumination',
    description: 'The glare whips an existing swarm into a frenzy, driving up what the victim owes to be rid of it. Does nothing extra if they have no Fireflies.',
    hotkey: 'F',
    kind: 'attack',
    element: 'light',
    color: '#f7f7f2',
    gradient: 'linear-gradient(135deg, #9a9a93, #f7f7f2)',
    icon: FaLightbulb,
  },
  flashBang: {
    id: 'flashBang',
    name: 'Flash Bang',
    description: 'A blinding pop that stretches every cooldown already running on every kingdom. Abilities sitting ready are untouched, so it only bites a field that has just spent its kit.',
    hotkey: 'R',
    kind: 'utility',
    element: 'light',
    color: '#f7f7f2',
    gradient: 'linear-gradient(135deg, #9a9a93, #f7f7f2)',
    icon: GiFlashGrenade,
  },
  lightShow: {
    id: 'lightShow',
    name: 'Light Show',
    description: 'The sky lights up and comes down on everyone 3 seconds later. Any kingdom without a shield when it lands takes heavy damage; a shielded one loses its shield outright, whatever its health, and takes nothing.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'light',
    color: '#f7f7f2',
    gradient: 'linear-gradient(135deg, #9a9a93, #f7f7f2)',
    icon: GiLighthouse,
  },
  // Dark Abilities — PLACEHOLDER (see Server/src/data/darkAbilities.ts)
  shadowStrike: {
    id: 'shadowStrike',
    name: 'Shadow Strike',
    description: 'Basic Dark attack. A strike out of your own shadow.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'dark',
    color: '#12121a',
    gradient: 'linear-gradient(135deg, #050508, #12121a, #f7f7f2)',
    icon: BsShadows,
  },
  yinAndYang: {
    id: 'yinAndYang',
    name: 'Yin and Yang',
    description: 'Call a side, and your victim loses either way. Yin punishes them for hiring a citizen; Yang punishes them for refusing to. Choosing correctly halves the damage. Settles the moment they hire, or when the window closes.',
    hotkey: 'E',
    kind: 'attack',
    element: 'dark',
    color: '#12121a',
    gradient: 'linear-gradient(135deg, #050508, #12121a, #f7f7f2)',
    icon: FaYinYang,
    choices: [
      { value: 'yin', label: 'Yin', hint: 'Punish them for HIRING a citizen' },
      { value: 'yang', label: 'Yang', hint: 'Punish them for NOT hiring a citizen' },
    ],
  },
  unlimitedRage: {
    id: 'unlimitedRage',
    name: 'Unlimited Rage',
    description: 'Every point of damage you absorb feeds the Rage meter — the harder you are hit, the faster it climbs. Unusable until completely full, then it returns everything at once and leaves the victim blind. Empties on use.',
    hotkey: 'F',
    kind: 'attack',
    element: 'dark',
    color: '#12121a',
    gradient: 'linear-gradient(135deg, #050508, #12121a, #f7f7f2)',
    icon: GiEvilLove,
  },
  neverEndingNightmare: {
    id: 'neverEndingNightmare',
    name: 'Never-ending Nightmare',
    description: 'Strip a kingdom back to its opening move: for their next 3 attacks they can cast nothing but their basic attack.',
    hotkey: 'R',
    kind: 'utility',
    element: 'dark',
    color: '#12121a',
    gradient: 'linear-gradient(135deg, #050508, #12121a, #f7f7f2)',
    icon: GiDreamCatcher,
  },
  infinitumTenebrae: {
    id: 'infinitumTenebrae',
    name: 'Infinitum Tenebrae',
    description: 'For 30 seconds your attacks can target up to three kingdoms at once and land on each in FULL — no damage split — hit 30% harder, and plunge the screen of everyone they touch into darkness.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'dark',
    color: '#12121a',
    gradient: 'linear-gradient(135deg, #050508, #12121a, #f7f7f2)',
    icon: GiDelighted,
  },

  // PLACEHOLDER kit — names, copy and icons land with the real design.
  foxSwipe: {
    id: 'foxSwipe',
    name: 'Fox Swipe',
    description: 'A clean hit that also adds progress to your Ancient Memory.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'kitsune',
    color: '#0f52ba',
    gradient: 'linear-gradient(135deg, #08183f, #0f52ba, #1b2f7a)',
    icon: GiFoxTail,
  },
  foxFire: {
    id: 'foxFire',
    name: 'Fox Fire',
    description: 'An enchanting volley that leaves a burn behind. Every attack the victim makes fans the flames hotter — and it stacks. Feeds your Ancient Memory.',
    hotkey: 'E',
    kind: 'attack',
    element: 'kitsune',
    color: '#0f52ba',
    gradient: 'linear-gradient(135deg, #08183f, #0f52ba, #1b2f7a)',
    icon: GiFire,
  },
  oldFriends: {
    id: 'oldFriends',
    name: 'Old Friends',
    description: 'Send an army of foxes towards an enemy. If a kingdom is shielded they do heavy damage. If a kingdom is not shielded they move IN and stay, gnawing away and feeding your Ancient Memory the whole time. Buying a shield is the only way to drive them off.',
    hotkey: 'F',
    kind: 'attack',
    element: 'kitsune',
    color: '#0f52ba',
    gradient: 'linear-gradient(135deg, #08183f, #0f52ba, #1b2f7a)',
    icon: GiFoxHead,
  },
  azureGuidance: {
    id: 'azureGuidance',
    name: 'Azure Guidance',
    description: 'Ancient Memory fills twice as fast for a short window — every source of it, not just the passive trickle.',
    hotkey: 'R',
    kind: 'utility',
    element: 'kitsune',
    color: '#0f52ba',
    gradient: 'linear-gradient(135deg, #08183f, #0f52ba, #1b2f7a)',
    icon: LuReceiptJapaneseYen,
  },
  kitsuneRush: {
    id: 'kitsuneRush',
    name: 'Kitsune Rush',
    description: 'Fifteen seconds at double speed: every cooldown runs twice as fast — including ones already counting down — and your gold production doubles. It cannot be bought. It becomes available the moment your Ancient Memory is completely full, and empties it.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'kitsune',
    color: '#0f52ba',
    gradient: 'linear-gradient(135deg, #08183f, #0f52ba, #1b2f7a)',
    icon: GiFox,
  },

  // Magma Abilities
  lavaPunch: {
    id: 'lavaPunch',
    name: 'Lava Punch',
    description: 'Basic Magma attack with a chance of burning the enemy.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'magma',
    color: '#a8320a',
    gradient: 'linear-gradient(135deg, #3d0f04, #a8320a, #ff7518)',
    icon: GiPunchBlast,
  },
  eruption: {
    id: 'eruption',
    name: 'Eruption',
    description: 'A volley of lava that hits hard, with a chance of leaving a burn.',
    hotkey: 'E',
    kind: 'attack',
    element: 'magma',
    color: '#a8320a',
    gradient: 'linear-gradient(135deg, #3d0f04, #a8320a, #ff7518)',
    icon: GiEruption,
  },
  floorIsLava: {
    id: 'floorIsLava',
    name: 'Floor is Lava',
    description: 'Set the whole battlefield alight: while active, all burn damage has increased damage for EVERY kingdom, and the ground itself burns every other kingdom for 1 a tick. While it burns you also deal 10% more damage with every attack.',
    hotkey: 'F',
    kind: 'utility',
    element: 'magma',
    color: '#a8320a',
    gradient: 'linear-gradient(135deg, #3d0f04, #a8320a, #ff7518)',
    icon: GiLava,
  },
  smokeScreen: {
    id: 'smokeScreen',
    name: 'Smoke Screen',
    description: 'Thick smoke rolls over every kingdom currently targeting you — blinding them and singeing them for a little damage.',
    hotkey: 'R',
    kind: 'utility',
    element: 'magma',
    color: '#a8320a',
    gradient: 'linear-gradient(135deg, #3d0f04, #a8320a, #ff7518)',
    icon: FaSmog,
  },
  theEndOfTheWorld: {
    id: 'theEndOfTheWorld',
    name: 'The End of the World',
    description: 'A volcano erupts in the middle of the battlefield. Every kingdom has 20 seconds to defeat it. If they fail, each kingdom takes heavy damage. Only one thing may hold the middle of the field: you cannot raise it while another kingdom’s centrepiece still stands.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'magma',
    color: '#a8320a',
    gradient: 'linear-gradient(135deg, #3d0f04, #a8320a, #ff7518)',
    icon: GiSmokingVolcano,
  },

  // Insects Abilities — PLACEHOLDER kit. Names, copy and icons all land with
  // the real design; what matters today is that the kingdom is fully playable,
  // so the ability bar has five real buttons rather than an empty rail.
  venomShot: {
    id: 'venomShot',
    name: 'Venom Shot',
    description: 'Basic Insect attack with a chance of leaving venom behind. Venom stacks, so a kingdom that keeps eating this bleeds progressively harder.',
    hotkey: 'Q',
    kind: 'attack',
    element: 'insects',
    color: '#a8c020',
    gradient: 'linear-gradient(135deg, #3c4708, #a8c020, #d7e84a)',
    icon: BiBug,
  },
  butterflies: {
    id: 'butterflies',
    name: 'Butterflies',
    description: 'A heavy hit that leaves the target both softer and clumsier for 20 seconds: they take 10% more damage from everyone, and HALF of their own attacks now miss outright.',
    hotkey: 'E',
    kind: 'attack',
    element: 'insects',
    color: '#a8c020',
    gradient: 'linear-gradient(135deg, #3c4708, #a8c020, #d7e84a)',
    icon: PiButterflyFill,
  },
  infected: {
    id: 'infected',
    name: 'Infected',
    description: 'Heavy damage, and for 15 seconds any attack the target MISSES is deflected straight back into their own castle.',
    hotkey: 'F',
    kind: 'attack',
    element: 'insects',
    color: '#a8c020',
    gradient: 'linear-gradient(135deg, #3c4708, #a8c020, #d7e84a)',
    icon: GiInsectJaws,
  },
  creepyCrawlers: {
    id: 'creepyCrawlers',
    name: 'Creepy Crawlers',
    description: 'Send three bugs to crawl over an enemy’s screen, eating their gold the whole time. Each one takes two clicks to squash.',
    hotkey: 'R',
    kind: 'utility',
    element: 'insects',
    color: '#a8c020',
    gradient: 'linear-gradient(135deg, #3c4708, #a8c020, #d7e84a)',
    icon: GiHangingSpider,
  },
  caprice: {
    id: 'caprice',
    name: 'Caprice',
    description: 'A giant butterfly holds the middle of the battlefield for 25 seconds. While it is there everyone\'s target selection is scrambled. You are exempt and nobody can target YOU at all until it leaves. Only one thing may hold the middle of the field: you cannot send it out while another kingdom’s centrepiece still stands.',
    hotkey: 'Space',
    kind: 'ultimate',
    element: 'insects',
    color: '#a8c020',
    gradient: 'linear-gradient(135deg, #3c4708, #a8c020, #d7e84a)',
    icon: GiButterflyFlower,
  },
}

export function getAbilitiesForKingdom(kingdomId: string | null): ClientAbilityMetadata[] {
  if (!kingdomId) return []
  return Object.values(ABILITY_METADATA).filter((m) => m.element === kingdomId)
}
