import type { BoltNode, LightningConfig, Vec2 } from '../types'
import { ObjectPool, type PoolOptions } from '../pool'
import { distance } from '../trajectory'

// Lightning system (Epic 9). Electricity's Zap — a procedural lightning strike,
// reusable by stronger Electricity abilities. Deliberately NOT a fixed sprite:
//
//   • path     — generated by RECURSIVE MIDPOINT DISPLACEMENT so every strike
//     (and every frame of a strike) is a unique organic zig-zag; short segments
//     naturally get finer kinks. Some strikes read straight, others fork wildly.
//   • layers   — a wide additive purple GLOW blooms under a thin yellow-white
//     CORE; short unstable BRANCHES flick off interior nodes without ever
//     reaching the target.
//   • flicker  — the bolt lives ~60–120 ms and is REGENERATED every frame with
//     fresh randomness + fluctuating brightness, so it never sits static.
//   • impact   — optional short crackling arcs radiate from the strike point
//     (the flash / sparks / shake come from the EffectDefinition's burst).
//
// Path generation is pure (injectable rng), so it's unit-testable without a GPU;
// only the polyline drawing (BoltNode) is Pixi. Each module (path, branches,
// flicker envelope, impact arcs) is independent so future abilities can reuse it.

/** Everything about one live bolt except its (pooled) draw node. */
interface ActiveBolt {
  node: BoltNode
  from: Vec2
  to: Vec2
  config: LightningConfig
  elapsed: number
  /** Per-cast jaggedness scale so some bolts are straighter, others wilder. */
  jag: number
}

export class LightningSystem {
  private readonly pool: ObjectPool<BoltNode>
  private readonly items: ActiveBolt[] = []
  private readonly rng: () => number

  constructor(
    createNode: () => BoltNode,
    options: { rng?: () => number } & PoolOptions = {},
  ) {
    this.rng = options.rng ?? Math.random
    this.pool = new ObjectPool(
      createNode,
      (n) => n.clear(),
      { prewarm: options.prewarm ?? 6, maxIdle: options.maxIdle },
    )
  }

  /** Strike instantly from `from` to `to`, plus any impact arcs at the target. */
  spawn(config: LightningConfig, from: Vec2, to: Vec2): void {
    this.add(config, from, to)
    const arcs = config.impactArcs ?? 0
    const reach = distance(from, to)
    for (let i = 0; i < arcs; i++) {
      const angle = this.rng() * Math.PI * 2
      const len = reach * (0.1 + 0.12 * this.rng())
      const end = { x: to.x + Math.cos(angle) * len, y: to.y + Math.sin(angle) * len }
      // Arcs are shorter-lived, thinner, and branch-free crackle around the hit.
      this.add(
        {
          ...config,
          durationMs: config.durationMs * 0.7,
          glowWidth: config.glowWidth * 0.55,
          coreWidth: config.coreWidth * 0.7,
          branchChance: 0,
          impactArcs: 0,
          subdivisions: Math.max(2, config.subdivisions - 1),
        },
        to,
        end,
      )
    }
  }

  private add(config: LightningConfig, from: Vec2, to: Vec2): void {
    const node = this.pool.acquire()
    const item: ActiveBolt = {
      node,
      from: { x: from.x, y: from.y },
      to: { x: to.x, y: to.y },
      config,
      elapsed: 0,
      jag: config.jaggedness * (0.55 + 0.9 * this.rng()),
    }
    this.items.push(item)
    this.redraw(item)
  }

  update(dtMs: number): void {
    for (let i = this.items.length - 1; i >= 0; i--) {
      const b = this.items[i]!
      b.elapsed += dtMs
      if (b.elapsed >= b.config.durationMs) {
        this.pool.release(b.node) // pool reset clears the node
        this.items.splice(i, 1)
        continue
      }
      this.redraw(b) // flicker: fresh path + brightness every frame
    }
  }

  /** Regenerate the bolt's geometry + brightness for this frame. */
  private redraw(b: ActiveBolt): void {
    const { config } = b
    const t = config.durationMs <= 0 ? 1 : b.elapsed / config.durationMs
    // Rapid brightness fluctuation, fading toward the end of the short life.
    const fade = 1 - t * t
    const flicker = 0.55 + 0.45 * this.rng()
    const alpha = fade * flicker

    const main = generateBolt(b.from, b.to, b.jag, config.subdivisions, this.rng)
    const branches = generateBranches(main, config.branchChance, this.rng)

    b.node.draw([
      // Purple glow bloom (wide, soft).
      { paths: [main], width: config.glowWidth, color: config.glowColor, alpha: alpha * 0.5 },
      // Unstable branch crackle (thin, bright).
      { paths: branches, width: config.coreWidth * 0.7, color: config.coreColor, alpha: alpha * 0.85 },
      // Bright yellow-white core (thin, over the glow).
      { paths: [main], width: config.coreWidth, color: config.coreColor, alpha },
    ])
  }

  /** Number of bolts (main + arcs) currently alive. */
  get active(): number {
    return this.items.length
  }

  clear(): void {
    for (const b of this.items) this.pool.release(b.node)
    this.items.length = 0
  }
}

/**
 * Recursive midpoint displacement between `from` and `to`. Each pass splits
 * every segment and kicks the new midpoint sideways by up to `jaggedness × the
 * segment length`; because segments shorten each pass, the chaos self-refines.
 * Pure — the `rng` makes it testable and reproducible.
 */
export function generateBolt(
  from: Vec2,
  to: Vec2,
  jaggedness: number,
  subdivisions: number,
  rng: () => number,
): Vec2[] {
  let points: Vec2[] = [from, to]
  for (let s = 0; s < subdivisions; s++) {
    const next: Vec2[] = []
    for (let i = 0; i < points.length - 1; i++) {
      const a = points[i]!
      const b = points[i + 1]!
      next.push(a)
      const dx = b.x - a.x
      const dy = b.y - a.y
      const len = Math.hypot(dx, dy) || 1
      // Unit normal to the segment.
      const nx = -dy / len
      const ny = dx / len
      const offset = (rng() * 2 - 1) * len * jaggedness
      next.push({ x: (a.x + b.x) / 2 + nx * offset, y: (a.y + b.y) / 2 + ny * offset })
    }
    next.push(points[points.length - 1]!)
    points = next
  }
  return points
}

/**
 * Short branches flicking off interior nodes of the main bolt. Each veers away
 * at a random angle and dies partway — never reaching the target — so it reads
 * as instability, not extra reach. Pure.
 */
export function generateBranches(
  main: Vec2[],
  branchChance: number,
  rng: () => number,
): Vec2[][] {
  const branches: Vec2[][] = []
  if (branchChance <= 0 || main.length < 4) return branches
  for (let i = 2; i < main.length - 2; i++) {
    if (rng() >= branchChance) continue
    const start = main[i]!
    const prev = main[i - 1]!
    const baseAngle = Math.atan2(start.y - prev.y, start.x - prev.x)
    const angle = baseAngle + (rng() * 2 - 1) * 1.0 // veer up to ~57°
    // Length scaled off the local segment so branches stay small.
    const localLen = Math.hypot(start.x - prev.x, start.y - prev.y)
    const len = localLen * (2 + rng() * 3)
    const end = { x: start.x + Math.cos(angle) * len, y: start.y + Math.sin(angle) * len }
    branches.push(generateBolt(start, end, 0.35, 2, rng))
  }
  return branches
}
